const purpose = [
  ["01", "Human first", "Technology that amplifies human potential."], ["02", "Ethical by design", "Intelligence built with integrity and fairness."],
  ["03", "Space future", "Infrastructure for enduring life beyond Earth."], ["04", "Sustainable impact", "Systems that regenerate our planet and beyond."],
];
const pillars = [
  ["AI + Autonomy", "Adaptive intelligence that learns, assists and operates autonomously."], ["Quantum Systems", "Quantum computing and secure communications for the next era."],
  ["Biotech + Life Support", "Resilient life-support and biotechnology for space and Earth."], ["Energy + Sustainability", "Clean, abundant systems for a sustainable civilisation."],
];
const roadmap = [
  ["2025", "Foundation", "Research, align and establish core systems."], ["2026–27", "Development", "Build, test and validate products and pilots."],
  ["2028–30", "Scale", "Integrate, deploy and expand global collaboration."], ["2031–40", "Expansion", "Infrastructure, missions and deep-space reach."],
  ["2041–50+", "Legacy", "Sustain, evolve and inspire future generations."],
];
function Mark(){return <span className="mark" aria-hidden="true">Ω</span>}
export default function Home(){return <main>
  <header className="nav shell"><a className="brand" href="#home" aria-label="De-Omega-Point home"><Mark/><span><b>DE-OMEGA-POINT</b><small>HUMAN-VALUE CENTRIC INTELLIGENCE</small></span></a><nav aria-label="Primary navigation"><a className="active" href="#home">Home</a><a href="#mission">Mission</a><a href="#projects">Projects</a><a href="#technology">Technology</a><a href="#impact">Impact</a><a href="#company">Company</a><a href="#contact">Contact</a></nav><a className="button outline nav-cta" href="#contact">Join the future</a></header>
  <section className="hero" id="home"><div className="hero-art" aria-hidden="true"/><div className="shell hero-content"><p className="eyebrow">Intelligence beyond limits.</p><h1>Engineering<br/>humanity<br/><em>forward.</em></h1><p className="lede">De-Omega-Point designs and deploys human-value centric intelligence and space technologies that solve real-world problems and elevate humanity towards a sustainable future among the stars.</p><div className="actions"><a className="button primary" href="#mission">Explore our mission →</a><a className="button outline" href="#projects">View our projects</a></div><a className="scroll" href="#mission">↓ &nbsp; Scroll to explore</a></div></section>
  <section className="purpose shell panel" id="mission"><div className="section-intro"><p className="eyebrow">Our purpose</p><h2>To engineer a legacy that outlives generations.</h2></div><div className="purpose-grid">{purpose.map(([n,t,d])=><article key={t}><span className="number">{n}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}<article className="target"><span>Target year</span><strong>2050+</strong><p>Building the future. Together.</p></article></div></section>
  <section className="initiative shell panel" id="projects"><div className="initiative-main"><p className="eyebrow">Featured initiative</p><h2>Project Omega Horizon</h2><h3>The space industry initiative</h3><p>A multi-phase program building the intelligent infrastructure for humanity’s expansion into space and the utilisation of space for the benefit of life on Earth and beyond.</p><ul><li>Autonomous space systems</li><li>Orbital infrastructure and logistics</li><li>Lunar and planetary operations</li><li>Deep-space communication networks</li><li>Sustainable resource utilisation</li><li>Human–robot collaboration</li></ul><a className="button outline" href="#contact">Explore the initiative →</a></div><div className="initiative-art" role="img" aria-label="A future lunar settlement beneath Earth"/><aside><article><span>⌘</span><div><h3>Research focus</h3><p>Intelligent systems for space infrastructure and operations.</p></div></article><article><span>◈</span><div><h3>Collaboration</h3><p>Working with global partners, researchers and innovators.</p></div></article><article><span>◎</span><div><h3>Future impact</h3><p>Enabling sustainable human presence beyond Earth.</p></div></article></aside></section>
  <section className="roadmap shell panel" id="impact"><p className="eyebrow">Our roadmap to 2050+</p><div className="timeline">{roadmap.map(([year,title,desc])=><article key={year}><i/><strong>{year}</strong><h3>{title}</h3><p>{desc}</p></article>)}</div></section>
  <section className="technology shell" id="technology"><div className="tech-art" role="img" aria-label="Human and artificial intelligence looking towards Earth"/><div className="tech-content panel"><div className="section-intro"><p className="eyebrow">Our technology pillars</p></div><div className="pillar-grid">{pillars.map(([t,d],i)=><article key={t}><span className="tech-icon">0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="cta shell panel" id="contact"><div><h2>Let’s engineer <em>humanity forward.</em></h2><p>Partner with us. Invest in the future. Build a legacy.</p></div><div className="actions"><a className="button primary" href="mailto:contact@de-omega-point.com">Become a partner</a><a className="button outline" href="mailto:contact@de-omega-point.com?subject=Investment%20enquiry">Invest in the future</a><a className="button outline" href="mailto:contact@de-omega-point.com">Contact us</a></div></section>
  <footer className="shell" id="company"><a className="brand" href="#home"><Mark/><span><b>DE-OMEGA-POINT</b><small>HUMAN-VALUE CENTRIC INTELLIGENCE</small></span></a><p>© 2026 De-Omega-Point. All rights reserved.</p><div><a href="#mission">Privacy</a><a href="#mission">Terms</a><a href="#contact">Careers</a></div></footer>
</main>}
